# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/322/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /snap/clion/322/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jordan/CLionProjects/Linked-File-System-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jordan/CLionProjects/Linked-File-System-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1441/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/clion/322/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/CLionProjects/Linked-File-System-C/CMakeFiles /home/jordan/CLionProjects/Linked-File-System-C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordan/CLionProjects/Linked-File-System-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LinkedFS

# Build rule for target.
LinkedFS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkedFS
.PHONY : LinkedFS

# fast build rule for target.
LinkedFS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/build
.PHONY : LinkedFS/fast

#=============================================================================
# Target rules for targets named test_ui

# Build rule for target.
test_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ui
.PHONY : test_ui

# fast build rule for target.
test_ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/build
.PHONY : test_ui/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/build
.PHONY : unity/fast

lib/cJSON/cJSON.o: lib/cJSON/cJSON.c.o
.PHONY : lib/cJSON/cJSON.o

# target to build an object file
lib/cJSON/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/lib/cJSON/cJSON.c.o
.PHONY : lib/cJSON/cJSON.c.o

lib/cJSON/cJSON.i: lib/cJSON/cJSON.c.i
.PHONY : lib/cJSON/cJSON.i

# target to preprocess a source file
lib/cJSON/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/lib/cJSON/cJSON.c.i
.PHONY : lib/cJSON/cJSON.c.i

lib/cJSON/cJSON.s: lib/cJSON/cJSON.c.s
.PHONY : lib/cJSON/cJSON.s

# target to generate assembly for a file
lib/cJSON/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/lib/cJSON/cJSON.c.s
.PHONY : lib/cJSON/cJSON.c.s

lib/unity/unity.o: lib/unity/unity.c.o
.PHONY : lib/unity/unity.o

# target to build an object file
lib/unity/unity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/lib/unity/unity.c.o
.PHONY : lib/unity/unity.c.o

lib/unity/unity.i: lib/unity/unity.c.i
.PHONY : lib/unity/unity.i

# target to preprocess a source file
lib/unity/unity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/lib/unity/unity.c.i
.PHONY : lib/unity/unity.c.i

lib/unity/unity.s: lib/unity/unity.c.s
.PHONY : lib/unity/unity.s

# target to generate assembly for a file
lib/unity/unity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unity.dir/build.make CMakeFiles/unity.dir/lib/unity/unity.c.s
.PHONY : lib/unity/unity.c.s

src/ui/main_program.o: src/ui/main_program.c.o
.PHONY : src/ui/main_program.o

# target to build an object file
src/ui/main_program.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/main_program.c.o
.PHONY : src/ui/main_program.c.o

src/ui/main_program.i: src/ui/main_program.c.i
.PHONY : src/ui/main_program.i

# target to preprocess a source file
src/ui/main_program.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/main_program.c.i
.PHONY : src/ui/main_program.c.i

src/ui/main_program.s: src/ui/main_program.c.s
.PHONY : src/ui/main_program.s

# target to generate assembly for a file
src/ui/main_program.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/main_program.c.s
.PHONY : src/ui/main_program.c.s

src/ui/ui.o: src/ui/ui.c.o
.PHONY : src/ui/ui.o

# target to build an object file
src/ui/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/ui.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/ui/ui.c.o
.PHONY : src/ui/ui.c.o

src/ui/ui.i: src/ui/ui.c.i
.PHONY : src/ui/ui.i

# target to preprocess a source file
src/ui/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/ui.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/ui/ui.c.i
.PHONY : src/ui/ui.c.i

src/ui/ui.s: src/ui/ui.c.s
.PHONY : src/ui/ui.s

# target to generate assembly for a file
src/ui/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/ui/ui.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/ui/ui.c.s
.PHONY : src/ui/ui.c.s

src/util/file_operation.o: src/util/file_operation.c.o
.PHONY : src/util/file_operation.o

# target to build an object file
src/util/file_operation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_operation.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_operation.c.o
.PHONY : src/util/file_operation.c.o

src/util/file_operation.i: src/util/file_operation.c.i
.PHONY : src/util/file_operation.i

# target to preprocess a source file
src/util/file_operation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_operation.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_operation.c.i
.PHONY : src/util/file_operation.c.i

src/util/file_operation.s: src/util/file_operation.c.s
.PHONY : src/util/file_operation.s

# target to generate assembly for a file
src/util/file_operation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_operation.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_operation.c.s
.PHONY : src/util/file_operation.c.s

src/util/file_system.o: src/util/file_system.c.o
.PHONY : src/util/file_system.o

# target to build an object file
src/util/file_system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_system.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_system.c.o
.PHONY : src/util/file_system.c.o

src/util/file_system.i: src/util/file_system.c.i
.PHONY : src/util/file_system.i

# target to preprocess a source file
src/util/file_system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_system.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_system.c.i
.PHONY : src/util/file_system.c.i

src/util/file_system.s: src/util/file_system.c.s
.PHONY : src/util/file_system.s

# target to generate assembly for a file
src/util/file_system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/file_system.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/file_system.c.s
.PHONY : src/util/file_system.c.s

src/util/memory_management.o: src/util/memory_management.c.o
.PHONY : src/util/memory_management.o

# target to build an object file
src/util/memory_management.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/memory_management.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/memory_management.c.o
.PHONY : src/util/memory_management.c.o

src/util/memory_management.i: src/util/memory_management.c.i
.PHONY : src/util/memory_management.i

# target to preprocess a source file
src/util/memory_management.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/memory_management.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/memory_management.c.i
.PHONY : src/util/memory_management.c.i

src/util/memory_management.s: src/util/memory_management.c.s
.PHONY : src/util/memory_management.s

# target to generate assembly for a file
src/util/memory_management.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/memory_management.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/memory_management.c.s
.PHONY : src/util/memory_management.c.s

src/util/stack.o: src/util/stack.c.o
.PHONY : src/util/stack.o

# target to build an object file
src/util/stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/stack.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/stack.c.o
.PHONY : src/util/stack.c.o

src/util/stack.i: src/util/stack.c.i
.PHONY : src/util/stack.i

# target to preprocess a source file
src/util/stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/stack.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/stack.c.i
.PHONY : src/util/stack.c.i

src/util/stack.s: src/util/stack.c.s
.PHONY : src/util/stack.s

# target to generate assembly for a file
src/util/stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkedFS.dir/build.make CMakeFiles/LinkedFS.dir/src/util/stack.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/src/util/stack.c.s
.PHONY : src/util/stack.c.s

test/process_ui_commands_tests.o: test/process_ui_commands_tests.c.o
.PHONY : test/process_ui_commands_tests.o

# target to build an object file
test/process_ui_commands_tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/test/process_ui_commands_tests.c.o
.PHONY : test/process_ui_commands_tests.c.o

test/process_ui_commands_tests.i: test/process_ui_commands_tests.c.i
.PHONY : test/process_ui_commands_tests.i

# target to preprocess a source file
test/process_ui_commands_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/test/process_ui_commands_tests.c.i
.PHONY : test/process_ui_commands_tests.c.i

test/process_ui_commands_tests.s: test/process_ui_commands_tests.c.s
.PHONY : test/process_ui_commands_tests.s

# target to generate assembly for a file
test/process_ui_commands_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ui.dir/build.make CMakeFiles/test_ui.dir/test/process_ui_commands_tests.c.s
.PHONY : test/process_ui_commands_tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LinkedFS"
	@echo "... test_ui"
	@echo "... unity"
	@echo "... lib/cJSON/cJSON.o"
	@echo "... lib/cJSON/cJSON.i"
	@echo "... lib/cJSON/cJSON.s"
	@echo "... lib/unity/unity.o"
	@echo "... lib/unity/unity.i"
	@echo "... lib/unity/unity.s"
	@echo "... src/ui/main_program.o"
	@echo "... src/ui/main_program.i"
	@echo "... src/ui/main_program.s"
	@echo "... src/ui/ui.o"
	@echo "... src/ui/ui.i"
	@echo "... src/ui/ui.s"
	@echo "... src/util/file_operation.o"
	@echo "... src/util/file_operation.i"
	@echo "... src/util/file_operation.s"
	@echo "... src/util/file_system.o"
	@echo "... src/util/file_system.i"
	@echo "... src/util/file_system.s"
	@echo "... src/util/memory_management.o"
	@echo "... src/util/memory_management.i"
	@echo "... src/util/memory_management.s"
	@echo "... src/util/stack.o"
	@echo "... src/util/stack.i"
	@echo "... src/util/stack.s"
	@echo "... test/process_ui_commands_tests.o"
	@echo "... test/process_ui_commands_tests.i"
	@echo "... test/process_ui_commands_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

